version: '3'
services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile

    image: 'zitlallyalmazan/firstimage'
    ports:
      - '4500:3000'
    volumes:
      - .:/app
      - /app/.ebextensions